apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
spec:
  ingressClassName: nginx
  rules:
    - host: shoecart.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shoecart-service
                port:
                  number: 8000